[package]
name = "mirlvm"
version = "0.1.0"
authors = ["masashi <ym.atonement.oy999@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.7.2"
rand = "0.8.4"